import { Poppins } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Specify the weights you intend to use
  display: "swap",
  variable: "--font-poppins",
});

// const regularFont = localFont({
//   src: "/fonts/regular.otf",
//   variable: "--font-regular",
//   display: "swap",
// });

// const mediumFont = localFont({
//   src: "/fonts/medium.otf",
//   variable: "--font-medium",
//   display: "swap",
// });

// const lightFont = localFont({
//   src: "/fonts/light.otf",
//   variable: "--font-light",
//   display: "swap",
// });

// const boldFont = localFont({
//   src: "/fonts/bold.otf",
//   variable: "--font-bold",
//   display: "swap",
// });
export const metadata = {
  title: "Graphite space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
